#!/bin/bash
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

mkdir ../build/buildtemp
cp -R -v ../src/* ../build/buildtemp/
cd ../build/buildtemp/package
tar -cvzf package.tgz *
cp package.tgz ../
cd ..
rm -rf ./package
tar -cvf ../Subsonic616.spk *
cd ../../scripts
rm -rf ../build/buildtemp
